//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public string MaDV { get; set; }
        public string TenDV { get; set; }
        public string MaPhong { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
